### ISSUE TITLE
Sections of the Settings app are disabled after running the script

### ISSUE THREAD

**Issue by akbyrd** [Disassembler0/Win10-Initial-Setup-Script#84] opened 2018-04-23 01:53 UTC
After running the script, I'm seeing the following message in several places in the Settings app:
>Some settings are hidden or managed by your organization

I've tracked a few instances down:
DisableAdvertisingID : Settings > Privacy > General
DisableTailoredExperiences : Settings > Privacy > Diagnostics & feedback
DisableFeedback : Settings > Privacy > Diagnostics & feedback
DisableTelemetry : Settings > Privacy > Diagnostics & feedback
DisableLockScreen : Settings > Personalization > Lock screen

This is on the Spring Creators Update, build 1803

I'm not sure if this is a known thing, but I don't see any warnings or information that this will happen and it's not immediately obvious why I can't change some of my settings when encountering this for the first time.

**Comment by Disassembler0** [comment] 2018-04-23 05:17
Duplicate of #49. Also the FAQ mentions GPO being used and says with bold letters *If you're not sure what the script does, do not attempt to run it!* and you clearly were not sure. :)

But OK, I'll add the information to the FAQ stating that setting things via GPO (as some of the tweaks do to ensure the setting is correctly applied for all users and not overriden by updates) directly result in this message.

**Closed** 2018-05-05 15:06 UTC
Labels: duplicate
