### ISSUE TITLE
Some icons still remain on start menu after running script

### ISSUE THREAD

**Issue by Win10debloater** [Disassembler0/Win10-Initial-Setup-Script#185] opened 2018-12-17 15:39 UTC
Drawboard PDF,Minecraft,Township icons still remain in start menu after running script
![untitled](https://user-images.githubusercontent.com/45937301/50097426-94329f80-0222-11e9-974d-61cc5cc44291.png)

**Comment by Disassembler0** [comment] 2018-12-17 15:52
Duplicate of  #8, #38, #101, #145, #169.

**tl;dr:** There are apps which are installed (provisioned) and apps which are suggested. The provisioned ones can be uninstalled and that's what the script does. The suggested ones can't be uninstalled (because they are not installed) and have just a placeholder tile which runs the installation when user clicks on it. The extraneous icons for suggestions can be removed using `UnpinStartMenuTiles` tweak which is not included in the default preset because it irreversibly unpins all icons and if you want to revert, you have to do so manually.

**Closed by Disassembler0** 2018-12-17 15:52 UTC

**Comment by Disassembler0** [comment] 2018-12-17 15:54
...actually in this case it might just be that you're trying to apply the script when provisioning process is still running. That has also been explained in one of the linked issues.

**Comment by Win10debloater** [comment] 2018-12-17 17:07
Thank you for info,sorry for dublicate.
