### ISSUE TITLE
Something in my default preset is breaking the search function (Windows 1903)

### ISSUE THREAD

**Issue by pencilbook** [Disassembler0/Win10-Initial-Setup-Script#261] opened 2019-08-31 18:35 UTC
https://pastebin.com/TvUeGau7

Any idea?

**Comment by pencilbook** [comment] 2019-09-03 15:25
I found the issue, it's the DisableWebSearch. Disabling it will nuke the entire search function.

**Comment by Disassembler0** [comment] 2019-09-04 14:22
Closing as duplicate of #262.

(Even though this was opened sooner, the other has some ongoing discussion.)

**Closed by Disassembler0** 2019-09-04 14:22 UTC
