### ISSUE TITLE
system tray icons not grouping? i still need that

### ISSUE THREAD

**Issue by Dj-jom2x** [Disassembler0/Win10-Initial-Setup-Script#318] opened 2020-06-13 07:23 UTC

**Comment by Disassembler0** [comment] 2020-06-13 07:30
`ShowTrayIcons` / `HideTrayIcons` tweaks affect this. `ShowTrayIcons` is included in the default preset and causes the notification area (SysTray) icons to be visible at all times. So to get the arrow / grouping / hiding back either apply `HideTrayIcons` tweak or simply fix it manually by using the checkbox in *Settings* -> *Personalization* -> *Taskbar* -> *Select which icons appear on the taskbar* -> *Always show all icons in the notification area*

This seem to be a duplicate of #219 and partially #282.

**Closed** 2020-07-15 15:02 UTC
