### ISSUE TITLE
Can't change setting of Windows Insider

### ISSUE THREAD

**Issue by zLian17** [Disassembler0/Win10-Initial-Setup-Script#285] opened 2019-12-18 18:06 UTC
I joined insider,but Iast 2 months i didn't get any updates. In windows insider setting written (Some setting are hidden by organization through to Group Policy). It happened after i use this script. What thing should i do to the default.preset so that i can change the setting?

**Comment by Disassembler0** [comment] 2019-12-18 18:12
Did you use the default preset? If so, then this is a duplicate of #92 and you need to enable Telemetry using `EnableTelemetry` tweak. There is a note in `DisableTelemetry` mentioning Insider program which you have most likely didn't notice.
https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/317c49038941ccea1c74c6838bc1d383a1078341/Win10.psm1#L13

If you haven't applied `EnableTelemetry`, then please paste your preset.

**Comment by zLian17** [comment] 2019-12-18 18:19
> Did you use the default preset? If so, then this is a duplicate of #92 and you need to enable Telemetry using `EnableTelemetry` tweak. There is a note in `DisableTelemetry` mentioning Insider program which you have most likely didn't notice.
> https://github.com/Disassembler0/Win10-Initial-Setup-Script/blob/317c49038941ccea1c74c6838bc1d383a1078341/Win10.psm1#L13
> 
> If you haven't applied `EnableTelemetry`, then please paste your preset.

I have enabled telemetry and give it 3(full),diagtrack and wappush. But still with same problem

**Comment by Disassembler0** [comment] 2019-12-18 18:33
>I have enabled telemetry

Did you do it via GUI or using the tweak? Because the tweak sets a bunch of other registry keys which need to be reset too. (Also a reboot is needed afterwards, but you have probably done that.)

The "_Some settings are hidden or managed by your organization_" is expected, as you most likely have some other settings set via GPO too, so if you still see it that doesn't necessarily mean that the problem persists.

Other that that, two months is a long period, so maybe try to leave the insider program and re-enter it. But this is just a guess. Insider builds aren't supported by the script, so I have never tried to make it "insider-proof".

**Comment by zLian17** [comment] 2019-12-18 23:44
> > I have enabled telemetry
> 
> Did you do it via GUI or using the tweak? Because the tweak sets a bunch of other registry keys which need to be reset too. (Also a reboot is needed afterwards, but you have probably done that.)
> 
> The "_Some settings are hidden or managed by your organization_" is expected, as you most likely have some other settings set via GPO too, so if you still see it that doesn't necessarily mean that the problem persists.
> 
> Other that that, two months is a long period, so maybe try to leave the insider program and re-enter it. But this is just a guess. Insider builds aren't supported by the script, so I have never tried to make it "insider-proof".

I still searching the right GPO to change caused it said "...through the gpo setting"

**Closed** 2019-12-19 07:18 UTC
