### ISSUE TITLE
Very odd explorer issue

### ISSUE THREAD

**Issue by TheToolGuy** [Disassembler0/Win10-Initial-Setup-Script#249] opened 2019-06-11 10:29 UTC
I've tested this on 4 different machines (fresh installed Windows 10 Professional x64) and every single time I use even the default script settings, explorer acts weird.

Right mouse button menu navigating to **New** takes about 15 to 30 seconds to open the submenu for creating folders, new documents etc...
Could not find why it takes so long ...

All machines have SSD only and 8Gb ram or more.
I can't imagine I'm the only one with this weird behavior after running this.

Before running this, it's snappy.

**Comment by entdark** [comment] 2019-06-11 11:40
If you are on 1903 update you can run Windows 10 sandbox to test the script.
Just comment out all lines and uncomment one by one until you find the one that brings the issue.
Also I have seen many complaints about lagging context menu in explorer on Windows10 subreddit - you can try to find extra information there.

**Comment by Disassembler0** [comment] 2019-06-11 11:58
Can't reproduce on any of my VMs.

1. Which version/build do you use? 1903 or still 1809? Are those installation fully up-to-date? This was a known issue, but should have been fixed by [KB4482887](https://support.microsoft.com/en-us/help/4482887/windows-10-update-kb4482887).
2. Do you have any extra items in the menu besides the defaults? (Folder, Shortcut, BMP, RTF, TXT, ZIP)
3. If you create a new user account, does it happen there too?
4. Do you use any shell extensions, 3rd party shell customizations or other tweaking tools?

**Comment by TheToolGuy** [comment] 2019-06-11 13:11
1. It's on a **Clean** Windows 10 Pro x64 installation on all 4 different hardware machines.
    Tested and found on build 1809 and build 1903, all ms hotfixes applied.
2. Only the defaults when you install a **Clean** Windows 10 Pro x64 OS.
3. Yes. So it looks like an HKLM setting.
4. As stated above, it happens on a clean, fresh installed machine.

But I will try Endark's tip to get to the culprit, but that will take some time to complete...
("Just comment out all lines and uncomment one by one until you find the one that brings the issue.")

**Comment by TheToolGuy** [comment] 2019-06-11 13:52
Procedure I use for a fresh installation on vm's or hardware:

 * Install Windows using an MSDN iso / USB stick created with that same iso.
 * Run Windows Update as often as needed until all ms hotfixes are installed.
 * Final reboot
 * Testing the issue: It's not there.
 * Run your script.
 * Reboot
 * Testing the issue again: Bingo, it's there ...

**Comment by TheToolGuy** [comment] 2019-06-13 14:12
Oke, first things first ...

I used version 3.2, which has this odd behavior. (From that moment on.)

I tested all possible settings of version 3.7 (This latest one) and it's fast on the Desktop (creating a folder), but still slow on the hard drives. All my HDD are Samsung 850 Evo SSD ... It's slow even on formatted SSD ...

**Comment by c-rilaun** [comment] 2019-06-18 07:39
There's something between the chair and the keyboard ..
How do you execute the script ? By running the cmdlet individually or making your preset and executing it ? 

I also have a W10 Pro x64 with 850 Evo SSD (plus a M2 one and a SSHD) and i never have this issue, 3.2 or 3.7.

**Comment by entdark** [comment] 2019-06-18 10:10
Why don't you just enable every line in the script one by one as I advised before and finally find it out?
You could have already done that.

**Comment by c-rilaun** [comment] 2019-07-08 07:37
@TheToolGuy Any update on your issue mate ?

**Comment by TheToolGuy** [comment] 2019-07-08 08:49
Yes,

It seams to be working now, I reinstalled Windows and first thing I did was
running this.

The problem is not there so it must be other software that does this...

But I have until now, no clue which software this problem creates.

Conclusion:
There is nothing wrong with the scripts.

**Comment by c-rilaun** [comment] 2019-07-08 09:19
Ok, thanks for the reply mate.

**Closed** 2019-09-04 21:48 UTC
