### ISSUE TITLE
Disable Windows Defender "tamper protection disabled" warning

### ISSUE THREAD

**Issue by tendererdegree** [Disassembler0/Win10-Initial-Setup-Script#277] opened 2019-11-19 21:54 UTC
To fall in line with the function that disables the Microsoft account warning in windows defender, could we see a function that disables the tamper protection disabled warning?

**Comment by Disassembler0** [comment] 2019-11-19 21:56
Duplicate of #238. Related to #276.

**Closed by Disassembler0** 2019-11-19 21:56 UTC
