### ISSUE TITLE
Candy Crush, Cooking Fever, etc keep reappearing

### ISSUE THREAD

**Issue by jtbwatson** [Disassembler0/Win10-Initial-Setup-Script#126] opened 2018-08-08 15:28 UTC
As of Monday 8/6/18 I keep having consistent issues of Candy Crush and other bloat games not being removed. This wasn't a problem previously. It stays in the start menu, I right click and uninstall it, and it goes away until the next mouse click.

Just so you know, I'm doing everything in this order
1. Clean install Windows 10 1803 July .iso
2. Windows updates
3. Firmware/bios/drivers/etc
4. Software installs (chrome, firefox, ms office, java, silverlight, adobe reader)
5. this script

What are your thoughts?

**Comment by Disassembler0** [comment] 2018-08-08 15:38
Duplicate of #101

**Closed by Disassembler0** 2018-08-08 15:38 UTC
