### ISSUE TITLE
Task View No Longer works

### ISSUE THREAD

**Issue by tryptc** [Disassembler0/Win10-Initial-Setup-Script#174] opened 2018-11-16 16:05 UTC
Windows Task View no longer works.

I have re-enabled a few of the visuals that come with windows. When I try to use the Task View button, or press "Windows" + "Tab", explorer.exe crashes and restarts in an instant. Interestingly, I also see the volume slider pop up during this explorer restart

I have tried to delete the following entries from the registry, hoping that they would help:

"HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "EnableActivityFeed"

"HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "PublishUserActivities"

"HKLM:\SOFTWARE\Policies\Microsoft\Windows\System" -Name "UploadUserActivities"

I love the script!

**Comment by Disassembler0** [comment] 2018-11-16 16:11
Duplicate of #172.

Please run
```
Set-Service "CDPUserSvc" -StartupType Automatic
```

and reboot.

**Closed by Disassembler0** 2018-11-16 16:11 UTC
